version: "3.8"

services:
    main_database:
        image: postgres:15.5
        restart: always
        ports:
            - 5430:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: application
        volumes:
            - ./tests/database/maindb:/docker-entrypoint-initdb.d
        networks:
            - net_tenant

    client_database:
        image: postgres:15.5
        restart: always
        ports:
            - 5431:5432
        environment:
            POSTGRES_USER: client
            POSTGRES_PASSWORD: client
            POSTGRES_DB: client_tenant
        networks:
            - net_tenant

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        ports:
            - 6000:80
        environment:
            PGADMIN_DEFAULT_EMAIL: benchmark@admin.com
            PGADMIN_DEFAULT_PASSWORD: postgres
        depends_on:
            - main_database
        networks:
            - net_tenant

networks:
    net_tenant:
        driver: bridge
